# Generated by Django 3.2.25 on 2024-04-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isEmailConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
