# Generated by Django 3.2.25 on 2024-04-23 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default='32ea0088-0ec7-4435-aab2-dd7a434ebcaf', on_delete=django.db.models.deletion.CASCADE, to='core.usertype'),
            preserve_default=False,
        ),
    ]
