# Generated by Django 3.2.25 on 2024-04-26 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Old', 'Old'), ('Used', 'Used'), ('Used(Like New)', 'Used(Like New)')], max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('display_image_path', models.CharField(max_length=255)),
                ('isFree', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('short_info', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft'), ('Swapped', 'Swapped')], max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sub_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
