# Generated by Django 3.2.25 on 2024-04-30 02:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='display_image_path',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.item_image_file_path),
        ),
    ]
