# Generated by Django 3.2.25 on 2024-04-30 05:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240430_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cover_photo_path',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image_path',
        ),
        migrations.AddField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to=core.models.user_images_file_path),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=core.models.user_images_file_path),
        ),
    ]
