# Generated by Django 3.2.25 on 2024-05-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
