# Generated by Django 3.2.25 on 2024-05-10 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_itemimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemImages',
            new_name='ItemImage',
        ),
    ]
