# Generated by Django 3.2.25 on 2024-05-14 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='user',
            field=models.ForeignKey(default='cb7d02c9-2519-472b-8cde-589491bd460a', on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
    ]
